name: Deploy snake on push to main
on:
  push:
    branches:
      - main
jobs:
  deploy-with-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: deckele/react-snake
